### PR TITLE
Adds 4.8 kernel and rt1 patch to musnix

### PR DESCRIPTION
**Pull request by erlandsona**
I'm actually building this right now... so you might want to get back to me tomorrow to see how things went?

### CODE REVIEW

**Comment by erlandsona** [comment]
PS: I'm new to building the linux kernel... thankfully with this setup it's easy. That said, I had no idea it would take so long? Like a solid hour or more, I haven't really been paying attention. That's normal though right?

**Comment by henrytill** [comment]
Hi @erlandsona - thanks for this.  I'll try to review this today.

> That's normal though right?

Yes, that is normal.

**Comment by erlandsona** [comment]
So I had to update this PR with the modDirVersion param... I wasn't able to boot my machine after building the kernel with the modDirVersion set to "4.8.0-rt1"... so I tried setting it back to "4.8-rt1" and it's building now... we'll see if it works?

**Comment by erlandsona** [comment]
Yup so nothing's worked thus far... I'm a bit lost to be honest. Would love some tips...

**Comment by henrytill** [comment]
I ran into a different set of issues when trying to test these changes locally, but haven't had the time to take a closer look.  I'll try to dig into this over the weekend.

**Comment by tg-x** [comment]
the kernel and all the modules gets built, but no modules ends up installed at $out//lib/modules/4.8.0-rt1

**Comment by tg-x** [comment]
see build log:
[nix-store -l /nix/store/m5z9vk9cbzvd9937daz4g781vw6449y5-linux-4.8-rt1](https://github.com/musnix/musnix/files/531372/m5z9vk9cbzvd9937daz4g781vw6449y5-linux-4.8-rt1.log.txt)

note the error during install:
`make[2]: execvp: /nix/store/28wl3f34vfjpw0y5809bgr6382wqdscf-bash-4.3-p48/bin/bash: Argument list too long`

**Comment by tg-x** [comment]
this is already [fixed](https://github.com/NixOS/nixpkgs/commit/f19c961b4e461da045f2e72e73701059e5117be0) with a patch, which is added to kernelPatches

**Comment by erlandsona** [comment]
Closing as @tg-x has the proper fix for the build errors. :+1: @tg-x

**Pull request closed without merging**
