### PR TITLE
kernel: 4.14.12-rt10 -> 4.14.15-rt13

### PR DESCRIPTION
**Pull request by magnetophon**
4.14.15-rt12 builds and runs, but when I reboot, it hangs.
4.14.15-rt13 seems fine.

### CODE REVIEW

**Comment by henrytill** [comment]
Any updates?

**Comment by magnetophon** [comment]
No, haven't tried anything related yet.
Have you built this?  Does it reboot for you?

**Comment by magnetophon** [comment]
In the meantime a new release came out, which fixes things.
 I've edited the title and first comment to reflect this.

**Comment by henrytill** [comment]
> Have you built this? Does it reboot for you?

I hadn't had a chance to test yet, but it looks like our problem has been solved...

**Pull request merged**
