### PR TITLE
README: prefer installation via nix-channel

### PR DESCRIPTION
**Pull request by yegortimoshenko**
That will make it much easier to install and update musnix.

/cc @erlandsona

### CODE REVIEW

**Comment by erlandsona** [comment]
@yegortimoshenko Hey thanks a ton! I don't know if you saw my most recent issue. But apparently the nvidia drivers don't support the PREEMPT_RT patch without some patching themselves? 
Are you aware or savvy of those issues?

**Comment by henrytill** [comment]
Hey @yegortimoshenko, thanks for the PR.  This is a great idea!

I agree that this should be the recommended method of installation, but it might also be good to include the "old" approach, just so people are aware of the options.

**Comment by yegortimoshenko** [comment]
I think the previously used approach is inferior in that it couples requirement on musnix with a specific version of musnix, making it impossible to e.g. test patches without mutating musnix directory. The previous approach also made automatic updates impossible, other than having a cronjob running `git pull`.

With suggested approach, when someone wants to make, or test a patch for musnix, they can specify a custom path to musnix, e.g. `sudo nixos-rebuild -I musnix=/home/ophelia/musnix switch`, or for example `sudo nixos-rebuild -I musnix=https://github.com/magnetophon/musnix/archive/master.tar.gz switch` to test new kernel update by @magnetophon.

**Comment by henrytill** [comment]
These are very convincing points, much appreciated.

**Pull request merged**
