### PR TITLE
Add kernels 5.4 and 5.6

### PR DESCRIPTION
**Pull request by magnetophon**

### CODE REVIEW

**Comment by henrytill** [comment]
Fixed conflict resulting from my alignment fix patch.

**Comment by orivej** [comment]
Can you build these kernels? I get this error with `musnix.kernel.realtime = true;`:
```
error: option not set correctly: PREEMPT (wanted 'y', got 'n') 
error: unused option: PREEMPT_RT_FULL            
```
It seems that `PREEMPT_RT_FULL` was renamed to `PREEMPT_RT`. If I rename it in `modules/kernel.nix` I get:
```
error: unused option: PREEMPT_RT
error: option not set correctly: PREEMPT_VOLUNTARY (wanted 'y', got 'n')
```
I have figured out that `PREEMPT_RT` needs `EXPERT`. With `EXPERT = yes;` I get:
```
error: option not set correctly: PREEMPT (wanted 'y', got 'n')
error: option not set correctly: PREEMPT_RT (wanted 'y', got 'n')
```
I have changed `PREEMPT = no;` to `PREEMPT = yes;` in case it became incompatible with `PREEMPT_RT` and ended up with the single error that I don't know how to fix:
```
error: option not set correctly: PREEMPT_RT (wanted 'y', got 'n')
```

**Comment by equill** [comment]
Works for me in Unstable.

**Comment by magnetophon** [comment]
Works for me too on unstable.
@orivej Which nixos version are you on?

**Comment by orivej** [comment]
I am trying to build with the [current master](https://github.com/NixOS/nixpkgs/commit/63d98cab9badccc2c76dc16b15a3c68e0b7eca4e).

**Comment by orivej** [comment]
What is your `uname -a` and `zgrep PREEMPT /proc/config.gz`? I expect that PREEMPT_RT_FULL should not be there because it is no longer in the patches.

**Comment by magnetophon** [comment]
```
uname -a
Linux thinknix-rt 5.6.14-rt7 #1-NixOS SMP PREEMPT Wed May 20 06:22:38 UTC 2020 x86_64 GNU/Linux
```

```
zgrep PREEMPT /proc/config.gz
CONFIG_HAVE_PREEMPT_LAZY=y
# CONFIG_PREEMPT_NONE is not set
# CONFIG_PREEMPT_VOLUNTARY is not set
CONFIG_PREEMPT=y
CONFIG_PREEMPT_COUNT=y
CONFIG_PREEMPTION=y
CONFIG_PREEMPT_RCU=y
CONFIG_PREEMPT_NOTIFIERS=y
CONFIG_DRM_I915_PREEMPT_TIMEOUT=640
CONFIG_DEBUG_PREEMPT=y
# CONFIG_PREEMPTIRQ_EVENTS is not set
# CONFIG_PREEMPT_TRACER is not set
CONFIG_PREEMPTIRQ_DELAY_TEST=m
```

**Comment by orivej** [comment]
I can not quiet explain no error in your case, nevertheless you seem not to have a realtime-preemptible kernel (no CONFIG_PREEMPT_RT or CONFIG_PREEMPT_FULL). I have fixed my error in #113 (with the main ingredient being `lib.mkForce` to override the nixpkgs configuration), with it and #114 I have:
```
Linux orivej 5.6.17-rt9 #1-NixOS SMP PREEMPT_RT Sun Jun 7 11:16:49 UTC 2020 x86_64 GNU/Linux
```
```
CONFIG_HAVE_PREEMPT_LAZY=y
CONFIG_PREEMPT_LAZY=y
# CONFIG_PREEMPT_NONE is not set
# CONFIG_PREEMPT_VOLUNTARY is not set
# CONFIG_PREEMPT is not set
CONFIG_PREEMPT_RT=y
CONFIG_PREEMPT_COUNT=y
CONFIG_PREEMPTION=y
CONFIG_PREEMPT_RCU=y
CONFIG_PREEMPT_NOTIFIERS=y
CONFIG_DRM_I915_PREEMPT_TIMEOUT=640
CONFIG_DEBUG_PREEMPT=y
# CONFIG_PREEMPTIRQ_EVENTS is not set
# CONFIG_PREEMPT_TRACER is not set
CONFIG_PREEMPTIRQ_DELAY_TEST=m
```

**Pull request merged**
