### PR TITLE
kernel: add 4.18.5-rt3

### PR DESCRIPTION
**Pull request by magnetophon**
fixup README

### CODE REVIEW

**Comment by henrytill** [comment]
Seems you might have overwritten the intended change in this PR.  :smile:

**Comment by henrytill** [comment]
If you want to just rename the PR, this looks totally mergeable otherwise!

**Comment by magnetophon** [comment]
ok :)

**Comment by henrytill** [comment]
But the changes seem to be:
```
kernel: add 4.18.5-rt3
```

**Comment by magnetophon** [comment]
oh, sorry, lemme fix that

**Pull request merged**
