### PR TITLE
Flake: Initial Musnix Flake support

### PR DESCRIPTION
**Pull request by cidkidnix**
NixOS flake support for musnix, will function the same way as regular nix-channel or clone.

### CODE REVIEW

**Comment by cidkidnix** [comment]
Tell me if you need more explanation on the README, as I can add it if needed

**Comment by magnetophon** [comment]
Thanks!

As mentioned in your other PR, I'm probably not the target audience, but as is, I'm not following.
The readme doesn't even mention the two flake files.

There are users of musnix on both stable and unstable, and so far we've managed to make it work for both.
Is that possible here as well?

**Comment by cidkidnix** [comment]
Ah right, so the readme does have the only flake file you'll need. The flake in repo is automatically "imported" (for a better lack of words) when added to the config in the way I show in the README

**Comment by magnetophon** [comment]
Thanks, now even I get it!  ;)

**Comment by cidkidnix** [comment]
cc @magnetophon if you could can you test https://github.com/cidkidnix/musnix/tree/flake-rework for me? and make sure non-flake configs aren't broken? I'll open a PR for that after this one is merged (as it's based off of this one)

**Comment by magnetophon** [comment]
@cidkidnix I get:
```
nixos-rebuild test
error: value is a path while a list was expected, at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:283:19
(use '--show-trace' to show detailed location information)
building Nix...
error: value is a path while a list was expected, at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:283:19
(use '--show-trace' to show detailed location information)
building the system configuration...
error: value is a path while a list was expected, at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:283:19
(use '--show-trace' to show detailed location information)
```


With trace:
```
nixos-rebuild test --show-trace

error: while evaluating the attribute 'config' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/lib/eval-config.nix:64:5:
while evaluating 'evalModules' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:63:17, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/lib/eval-config.nix:58:12:
while evaluating 'mapAttrsRecursiveCond' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:293:36, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:140:28:
while evaluating 'recurse' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:295:23, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:303:8:
while evaluating the attribute 'matchedOptions' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:427:14:
while evaluating 'flip' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/trivial.nix:138:16, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:395:23:
while evaluating 'byName' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:364:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:383:21:
while evaluating 'reverseList' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:393:17, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:132:33:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:253:37, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:128:25:
while evaluating 'filterModules' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:243:36, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:254:7:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:247:31, called from undefined position:
while evaluating the attribute 'disabled' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:225:13:
while evaluating the attribute 'disabled' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:225:13:
while evaluating the attribute 'disabled' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:225:13:
while evaluating 'imap1' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:116:14, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:228:73:
while evaluating the attribute 'imports' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:283:9:
value is a path while a list was expected, at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:283:19
building Nix...
error: while evaluating the attribute 'config' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/lib/eval-config.nix:64:5:
while evaluating 'evalModules' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:63:17, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/lib/eval-config.nix:58:12:
while evaluating 'mapAttrsRecursiveCond' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:293:36, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:140:28:
while evaluating 'recurse' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:295:23, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:303:8:
while evaluating the attribute 'matchedOptions' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:427:14:
while evaluating 'flip' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/trivial.nix:138:16, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:395:23:
while evaluating 'byName' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:364:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:383:21:
while evaluating 'reverseList' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:393:17, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:132:33:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:253:37, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:128:25:
while evaluating 'filterModules' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:243:36, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:254:7:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:247:31, called from undefined position:
while evaluating the attribute 'disabled' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:225:13:
while evaluating the attribute 'disabled' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:225:13:
while evaluating the attribute 'disabled' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:225:13:
while evaluating 'imap1' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:116:14, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:228:73:
while evaluating the attribute 'imports' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:283:9:
value is a path while a list was expected, at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:283:19
building the system configuration...
error: while evaluating the attribute 'config.system.build.toplevel' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/lib/eval-config.nix:64:5:
while evaluating 'evalModules' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:63:17, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/lib/eval-config.nix:58:12:
while evaluating 'mapAttrsRecursiveCond' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:293:36, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:140:28:
while evaluating 'recurse' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:295:23, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:303:8:
while evaluating the attribute 'matchedOptions' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:427:14:
while evaluating 'flip' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/trivial.nix:138:16, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:395:23:
while evaluating 'byName' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:364:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:383:21:
while evaluating 'reverseList' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:393:17, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:132:33:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:253:37, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:128:25:
while evaluating 'filterModules' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:243:36, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:254:7:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:247:31, called from undefined position:
while evaluating the attribute 'disabled' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:225:13:
while evaluating the attribute 'disabled' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:225:13:
while evaluating the attribute 'disabled' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:225:13:
while evaluating 'imap1' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:116:14, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:228:73:
while evaluating the attribute 'imports' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:283:9:
value is a path while a list was expected, at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:283:19
```

**Comment by cidkidnix** [comment]
I made a typo I'll push a fix to the branch when I get home

**Comment by cidkidnix** [comment]
This PR should be ready to go with no breakage. We can wait for testers if needed.

**Comment by magnetophon** [comment]
Yes, this time around it works for non-flake configs.
Thanks!

**Comment by Narice** [comment]
It works for flake-based configs, so it is definitely awesome :yum:!

**Comment by henrytill** [comment]
Awesome work, much obliged!

**Pull request merged**
