### PR TITLE
Add musnix.rtcsq.enable option and related test

### PR DESCRIPTION
**Pull request by mcdonc**
I made this its own option, but I'd be ok with it if folks wanted to make it part of ``musnix.enable``.

One thing this helps with is detecting problems with config in the test.  It currently exposes a missing udev rule, which I hope to supply a fix for in an additional PR.

### CODE REVIEW

**Comment by henrytill** [comment]
Looks like a good addition.

However, running `nix-build tests/default.nix` gives me:
[Uploading output.txt…]()

**Comment by mcdonc** [comment]
I suspect the reason we get different results might be due to the lookup of "nixpkgs" under the invocation of `nix-build`.  Since it's using `nix-build` and not the new `nix <foo` regime, it's not using the package's flake inputs, it's relying on whatever is on the NIX_PATH, right?

I'll try to fix it in default.nix but I may wind up fixing it the wrong way, because it's possible we should both be invoking the test in some other way to know that we're apples to apples.

**Comment by mcdonc** [comment]
OK, sorry about that, I should have figured that although I didn't care about the gui portion of rtcqs, Nix might ;)  With any luck `nix-build test/default.nix` should work for you and anyone else.

**Comment by henrytill** [comment]
> OK, sorry about that, I should have figured that although I didn't care about the gui portion of rtcqs, Nix might ;) With any luck `nix-build test/default.nix` should now work for you and anyone else.

No problem!  I appreciate your efforts.

Unfortunately still not quite there on my machine:
[output.txt](https://github.com/musnix/musnix/files/14826959/output.txt)

I tried adding `pkgs.python3.pkgs.rsa` to `propagatedBuildInputs`, but it didn't fix the problem.

Here's my nixpkgs version:
```
"24.05pre604449.807c549feabc"
```

**Comment by mcdonc** [comment]
I've made an attempt at trying to make the tests pass for more folks in-situ; see the comments in the commit body for more info.  Hopefully this gets you further @henrytill .

In the meantime, I'm going to try to supply a different PR for review that offers a more apples to apples way to run the tests such that it won't matter how "<nixpkgs>" resolves for us.

**Comment by henrytill** [comment]
Could you rebase this against master now that #176 is merged?

**Comment by mcdonc** [comment]
I added a few more tests also.

**Comment by mcdonc** [comment]
Thanks Henry!

**Pull request merged**
