### PR TITLE
tests: update to use python testing harness

### PR DESCRIPTION
**Pull request by henrytill**
To run this test:
```
cd tests
nix-build
```

Ref:
https://nixos.org/nixos/manual/#sec-writing-nixos-tests

### CODE REVIEW

**Comment by magnetophon** [comment]
I get:

```
nix-build --max-jobs 4 --builders ''             
these derivations will be built:
  /nix/store/clp3hghlq6mip3njafm4dqglwdrndj6r-vm-test-run-unnamed.drv
building '/nix/store/clp3hghlq6mip3njafm4dqglwdrndj6r-vm-test-run-unnamed.drv'...
starting VDE switch for network 1
running the VM test script
machine: starting vm
machine # Formatting '/build/vm-state-machine/machine.qcow2', fmt=qcow2 size=536870912 cluster_size=65536 lazy_refcounts=off refco
_bits=16
machine: QEMU running (pid 9)
machine: waiting for the VM to finish booting
machine # qemu-system-x86_64: CPU model 'host' requires KVM
machine: connected to guest root shell
machine: (connecting took 0.00 seconds)
(0.00 seconds)
error: [Errno 32] Broken pipe
cleaning up
killing machine (pid 9)
(0.00 seconds)
builder for '/nix/store/clp3hghlq6mip3njafm4dqglwdrndj6r-vm-test-run-unnamed.drv' failed with exit code 1
error: build of '/nix/store/clp3hghlq6mip3njafm4dqglwdrndj6r-vm-test-run-unnamed.drv' failed
```

**Comment by henrytill** [comment]
> I get:
> 
> ```
> nix-build --max-jobs 4 --builders ''             
> these derivations will be built:
>   /nix/store/clp3hghlq6mip3njafm4dqglwdrndj6r-vm-test-run-unnamed.drv
> building '/nix/store/clp3hghlq6mip3njafm4dqglwdrndj6r-vm-test-run-unnamed.drv'...
> starting VDE switch for network 1
> running the VM test script
> machine: starting vm
> machine # Formatting '/build/vm-state-machine/machine.qcow2', fmt=qcow2 size=536870912 cluster_size=65536 lazy_refcounts=off refco
> _bits=16
> machine: QEMU running (pid 9)
> machine: waiting for the VM to finish booting
> machine # qemu-system-x86_64: CPU model 'host' requires KVM
> machine: connected to guest root shell
> machine: (connecting took 0.00 seconds)
> (0.00 seconds)
> error: [Errno 32] Broken pipe
> cleaning up
> killing machine (pid 9)
> (0.00 seconds)
> builder for '/nix/store/clp3hghlq6mip3njafm4dqglwdrndj6r-vm-test-run-unnamed.drv' failed with exit code 1
> error: build of '/nix/store/clp3hghlq6mip3njafm4dqglwdrndj6r-vm-test-run-unnamed.drv' failed
> ```

You may need to enable KVM support in your NixOS config.  I believe it's:
```
nix.systemFeatures = [ "kvm" <other-features> ]
```

(I haven't tested on a NixOS box yet, but it works fine on my Ubuntu 20.04 machine)

**Comment by magnetophon** [comment]
Ah, yes. I have KVM turned off, I think both in my BIOS and in my config.
I'll give it another shot.

**Comment by magnetophon** [comment]
Looks better now:

```
machine # [   14.530367] nscd[804]: 804 monitoring directory `/etc` (2)
machine # [   14.540965] systemd[1]: Reached target Network is Online.
machine # [   14.571374] nscd[804]: 804 disabled inotify-based monitoring for file `/etc/netgroup': No such file or directory
machine: must succeed: uname -v
machine # [   14.594426] systemd[1]: Reached target Multi-User System.
machine # [   14.600802] nscd[804]: 804 stat failed for file `/etc/netgroup'; will try again later: No such file or directory
(0.03 seconds)
#1-NixOS SMP PREEMPT Wed May 20 06:22:38 UTC 2020

machine: must succeed: uname -v
machine # [   14.615340] systemd[1]: Started Watchdog to ensure a realtime process won't hang the machine.
machine # [   14.630972] dhcpcd[615]: forked to background, child pid 818
(0.02 seconds)
(16.14 seconds)
machine # [   14.645548] systemd[1]: Starting IRQ thread tuning for realtime kernels...
machine # [   14.680832] das_watchdog[819]: started
test script finished in 16.22s
cleaning up
killing machine (pid 9)
(0.00 seconds)
```

Would be nice if there was a clear indication whether the test succeeded.

> (I haven't tested on a NixOS box yet, but it works fine on my Ubuntu 20.04 machine)

I thought  (assumed?) you where using NixOS on all your machines.
Are you (still?) using NixOS a lot?

**Comment by henrytill** [comment]
> I thought (assumed?) you where using NixOS on all your machines.
> Are you (still?) using NixOS a lot?

Alas, `<dayjob>` has meant that I'm primarily using Ubuntu these days.  Still use Nix on those machines tho.  My sole NixOS box developed some drive issues recently, and I haven't sorted them out yet.

**Pull request merged**
