### PR TITLE
kernel: add 4.8-rt1

### PR DESCRIPTION
**Pull request by tg-x**
with modinst_arg_list_too_long patch
that is missing from https://github.com/musnix/musnix/pull/36

### CODE REVIEW

**Comment by tg-x** [comment]
building, will report back when done

**Comment by henrytill** [comment]
@tg-x I look forward to yr report.  Thanks for digging into this.

**Comment by erlandsona** [comment]
Can't wait to try this out!!! I'll probably get to it later today... Will report back. Thanks @tg-x for figuring that out!

**Comment by erlandsona** [comment]
So nice thing was that I didn't have to rebuild the kernel for the extra patch to fix my computer not starting! :+1: @tg-x

**Comment by tg-x** [comment]
it did compile and started booting, but after a few seconds the whole system slowed down so much that it took at least half an hour or more just to get a root prompt..

then messages appeared about several million of printk messages dropped..
which could be the reason the whole thing slowed down so much..
saved some dmesg output which I stopped after several minutes and 400MB..
I'll extract useful parts of it and post it here..

**Comment by erlandsona** [comment]
@tg-x I'm confused, you're saying it doesn't work for you? Or should it not be working for me for some reason? How can I check if I actually got the kernel installed properly?

**Comment by tg-x** [comment]
here's some [dmesg output](https://github.com/musnix/musnix/files/531824/dmesg-4.8-rt-1.txt)

it seems the issue is around

`[<ffffffff9aa99af5>] migrate_enable+0x65/0x130`
`[<ffffffff9af5b647>] rt_spin_unlock+0x27/0x40`

a quick search shows some [LKML discussion](https://lkml.org/lkml/2016/10/3/244) about something similar,
 I won't dig into this further but wait for the next RT patch and try if that works..

**Comment by tg-x** [comment]
@erlandsona no, it doesn't work for me, does it work for you?
if you did not rebuild it then you probably on an older kernel..
check what `uname -a` says..

**Comment by tg-x** [comment]
(as a side note, the reason I was looking into this
because virtualbox kernel modules won't compile with 4.6-rt kernels,
which is fixed in 4.8, or can be also fixed for 4.6 with a [patch](https://www.spinics.net/lists/linux-rt-users/msg15592.html))

**Comment by erlandsona** [comment]
Here's output from my uname. It doesn't suggest I'm running anything rt, I just figured uname wasn't showing the flag?
```
❯ uname -a
Linux erlandsona 4.8.1 #1-NixOS SMP Fri Oct 7 13:03:33 UTC 2016 x86_64 GNU/Linux
```

**Comment by erlandsona** [comment]
I'm sticking with 4.8.1 though for now because it seems to fix an issue with my fan speed.

**Comment by tg-x** [comment]
4.8.2-rt2 is out, let's see if it works, build it now..

@erlandsona it should have -rt in there, you probably removed it from your config then..

should set
`musnix.kernel.packages = pkgs.linuxPackages_latest_rt;`
and should not set
`boot.kernelPackages`

**Comment by erlandsona** [comment]
I had boot.kernelPackages set to something I think... that makes sense. 👍 Thanks!

**Comment by tg-x** [comment]
just booted 4.8.2-rt2, same issues as with 4.8.0-rt1

**Comment by erlandsona** [comment]
@tg-x that's odd, it seemed to work just fine on my machine? Granted, I'm no expert and I'm probably doing something wrong.

**Comment by tg-x** [comment]
it's perfectly possible that this issue only occurs in certain cases and does not affect you

(didnt inspect it further, maybe something related to btrfs? there were also some btrfs-related functions in the backtrace..)

**Comment by henrytill** [comment]
@tg-x: How's `4.8.2-rt3` working for you?

**Comment by tg-x** [comment]
4.8.2-rt3 works, no longer have the issue above

**Comment by erlandsona** [comment]
Woot woot!

**Pull request merged**
