### PR TITLE
Add CLAP plugin path

### PR DESCRIPTION
**Pull request by bandithedoge**
Also sort environment variables alphanumerically

### CODE REVIEW

**Comment by magnetophon** [comment]
Thanks!
How can I test this?
I didn't know nixpkgs had any CLAP hosts or plugins, tbh!

**Comment by bandithedoge** [comment]
Actually there are quite a few CLAP plugins nixpkgs, including Cardinal, LSP plugins and CHOWTapeModel. Some good CLAP hosts in nixpkgs include Zrythm, Bitwig Studio (unfree) and REAPER (unfree).

**Shameless plug**: I have packaged some plugins and hosts in my [NUR repo](https://github.com/bandithedoge/nur-packages), all of them are built either from the latest commit or latest (pre-)release, so trying out, say, Cardinal nightly is a simple matter of `nix shell install github:bandithedoge/nur-packages#cardinal`. Other notable CLAP plugins from this repo include:
- [`tal.noisemaker` (unfree)](https://github.com/bandithedoge/nur-packages/blob/master/pkgs/tal/default.nix) (and other TAL plugins)
- [`distrho-ports`](https://github.com/bandithedoge/nur-packages/blob/master/pkgs/distrho-ports/default.nix) - Vitalium, old TAL plugins, etc; the version in nixpkgs is older than the CLAP standard itself
- [`dpf-plugins`](https://github.com/bandithedoge/nur-packages/blob/master/pkgs/dpf-plugins/default.nix)
- [`octasine`](https://github.com/bandithedoge/nur-packages/blob/master/pkgs/octasine/default.nix)

For hosts, consider the following:
- [`ildaeil`](https://github.com/bandithedoge/nur-packages/blob/master/pkgs/ildaeil/default.nix) - uses Carla nightly (with CLAP support) under the hood, also works as a plugin
- [`zrythm`](https://github.com/bandithedoge/nur-packages/blob/master/pkgs/zrythm/default.nix) - latest commit, nixpkgs doesn't quite keep up with Zrythm's fast development cycle

**Comment by henrytill** [comment]
Thanks for the contribution!

@magnetophon, I'm going to optimistically merge this, given that the change is relatively non-invasive.

**Comment by henrytill** [comment]
> > Thanks for the contribution!
> > @magnetophon, I'm going to optimistically merge this, given that the change is relatively non-invasive.
> 
> I was about to do that, and then I stopped and thought: what if I break Henrys repo? 😅

Fear not, simple enough to revert :laughing: 
 
> Plus I was quite busy with my new [limiter](https://github.com/magnetophon/lamb-rs)...

Nice!

**Comment by bandithedoge** [comment]
Thinking of it now, would it make sense to package some popular audio software in musnix? I could start by porting derivations from my repo.

**Comment by magnetophon** [comment]
Why not put them in nixpkgs?

**Comment by magnetophon** [comment]
> Actually there are quite a few CLAP plugins nixpkgs, including Cardinal, LSP plugins and CHOWTapeModel. Some good CLAP hosts in nixpkgs include Zrythm, Bitwig Studio (unfree) and REAPER (unfree).
> 
> **Shameless plug**: I have packaged some plugins and hosts in my [NUR repo](https://github.com/bandithedoge/nur-packages), all of them are built either from the latest commit or latest (pre-)release, so trying out, say, Cardinal nightly is a simple matter of `nix shell install github:bandithedoge/nur-packages#cardinal`. Other notable CLAP plugins from this repo include:
> 
> * [`tal.noisemaker` (unfree)](https://github.com/bandithedoge/nur-packages/blob/master/pkgs/tal/default.nix) (and other TAL plugins)
> * [`distrho-ports`](https://github.com/bandithedoge/nur-packages/blob/master/pkgs/distrho-ports/default.nix) - Vitalium, old TAL plugins, etc; the version in nixpkgs is older than the CLAP standard itself
> * [`dpf-plugins`](https://github.com/bandithedoge/nur-packages/blob/master/pkgs/dpf-plugins/default.nix)
> * [`octasine`](https://github.com/bandithedoge/nur-packages/blob/master/pkgs/octasine/default.nix)
> 
> For hosts, consider the following:
> 
> * [`ildaeil`](https://github.com/bandithedoge/nur-packages/blob/master/pkgs/ildaeil/default.nix) - uses Carla nightly (with CLAP support) under the hood, also works as a plugin
> * [`zrythm`](https://github.com/bandithedoge/nur-packages/blob/master/pkgs/zrythm/default.nix) - latest commit, nixpkgs doesn't quite keep up with Zrythm's fast development cycle

I just now noticed your answer to my question, sorry!
That also, at least partially explains my other question: because some of them have too new dependencies or are in beta.
But then the question remains, why in musnix and not in nur or similar?
Curious what Henry thinks.

**Comment by bandithedoge** [comment]
> I just now noticed your answer to my question, sorry, and thanks for the detailed answer!
> That also, at least partially explains my other question: because some of them have too new dependencies or are in beta.
> But then the question remains, why in musnix and not in nur or similar?
> Curious what Henry thinks.
>  

Technically they are already in the NUR namespace since my repo is included (although it disappeared from the website for whatever reason). Collecting them in musnix would make them much easier to find than some random guy's NUR packages, also it would be a great starting point for new musnix users to instantly make use of their newly acquired latency-optimized configurations. 

Not to mention it'd be a great way for us to distribute our own plugins for Nix users. ;)

The scope for a musnix package set would be strictly audio production software - DAWs, plugins, session managers, etc. Some of the hackier derivations would remain in NUR to make musnix a bit more curated and relatively plug-and-play. Then there's the question of unfree software and all the annoying ways it can be distributed but that's up to you to decide.

**Pull request merged**
