### PR TITLE
Linux 4.19.15-rt12 -> Linux 4.19.23-rt14 and latest rtirq

### PR DESCRIPTION
**Pull request by tex**
Update Linux kernel to latest RT patchset.
Musnix refers to no-longer existing version of rtirq, updated to the latest available.

### CODE REVIEW

**Comment by tex** [comment]
Don't merge it. This Kernel version and patches doesn't look very stable...

**Comment by magnetophon** [comment]
> This Kernel version and patches doesn't look very stable...

Could you explain? 

What about rtirq?

**Comment by tex** [comment]
Well, system instability.
Messages like `systemd-journald block for more then 120seconds`...
`dmesg` command does not print anything, but is hung indifinitely.
shutdown blocked indifinitely.

Will push rtirq in another push request separately.

**Comment by magnetophon** [comment]
Ok, thanks.

**Pull request closed without merging**
